#!/usr/bin/env bash

mkdir -p ~/.config/sops/age

# Temporary decrypt ed-key
cp $HOME/.ssh/id_ed25519 /tmp/id_ed25519
ssh-keygen -p -N "" -f /tmp/id_ed25519

# Generate sops age keys
nix-shell -p ssh-to-age --run "ssh-to-age -private-key -i /tmp/id_ed25519 > ~/.config/sops/age/keys.txt"

# Cleanup
rm /tmp/id_ed25519
