#!/usr/bin/env bash

sabit_ed="35e193fb-f78f-4372-a617-b33400be006d"
sabit_rsa="9381f8f2-eeb1-44e2-9b84-b33400be40eb"
box_ed="4c002466-aa69-4987-b70f-b33400fbef32"

mkdir -p ~/.ssh

rbw get --field private_key $sabit_ed >~/.ssh/id_ed25519
rbw get --field public_key $sabit_ed >~/.ssh/id_ed25519.pub
chmod 600 ~/.ssh/id_ed25519
chmod 644 ~/.ssh/id_ed25519.pub

rbw get --field private_key $sabit_rsa >~/.ssh/id_rsa
rbw get --field public_key $sabit_rsa >~/.ssh/id_rsa.pub
chmod 600 ~/.ssh/id_rsa
chmod 644 ~/.ssh/id_rsa.pub

rbw get --field private_key $box_ed | sudo tee /etc/ssh/ssh_host_ed25519_key
rbw get --field public_key $box_ed | sudo tee /etc/ssh/ssh_host_ed25519_key.pub
sudo chmod 600 /etc/ssh/ssh_host_ed25519_key
sudo chmod 644 /etc/ssh/ssh_host_ed25519_key.pub
