#!/usr/bin/env bash

# Print user public key
echo '&sabit' $(nix-shell -p ssh-to-age --run "ssh-to-age < ~/.ssh/id_ed25519.pub")

# Print host public key
echo '&box' $(nix-shell -p ssh-to-age --run "ssh-to-age < /etc/ssh/ssh_host_ed25519_key.pub")
